version: '3'

services:
  test-web-module:
    container_name: test-web-module
    build:
      context: ${BUILD_CONTEXT}/test-web-module
    image: 'test-web-module'
    ports:
      - '15030:8030'
    networks:
      frontend:
        aliases:
          - 'test-web-module'

  test-nginx:
    depends_on:
      - test-web-module
    container_name: test-nginx
    build:
      context: ${BUILD_CONTEXT}/test-nginx
    image: 'nginx'
    ports:
      - '15080:80'
      - '15043:443'
    networks:
      frontend:
        aliases:
          - 'test-nginx'
      
networks:
  frontend:
    driver: bridge
